// Generated by CoffeeScript 1.12.6
(function() {
  this.genModal = function(name, emp, rel, exp) {
    $(document).ready(function() {
      $('#majorName').html(name);
      $('#emp').html(emp + '%');
      $('#rel').html(rel + '%');
      $('#exp').html(exp + '%');
      $('[data-remodal-id=statsModal]').remodal().open();
    });
  };

}).call(this);

//# sourceMappingURL=gen-modal.js.map
